name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install eksctl
        run: |
          sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version

      - uses: azure/setup-kubectl@v3
        with:
           version: 'v1.15.0'
        id: install

      - name: Deploy Cluster
        run: |
          cd /home/runner/work/mah-assessment/mah-assessment/cluster
          eksctl create cluster --config-file mha-assessment-cluster.yaml

      - name: Deploy NGINX
        run: |
          pwd
          ls
          cd /home/runner/work/mah-assessment/mah-assessment/deployment
          kubectl apply -f nginx-deployment.yaml
          kubectl get svc
